package kotlinmdl.material.style

interface IMaterialIcons {

    // region Action
    val threeDRotation: IMaterialIcon
    val accessibility: IMaterialIcon
    val accessible: IMaterialIcon
    val accountBalance: IMaterialIcon
    val accountBalanceWallet: IMaterialIcon
    val accountBox: IMaterialIcon
    val accountCircle: IMaterialIcon
    val addShoppingCart: IMaterialIcon
    val alarm: IMaterialIcon
    val alarmAdd: IMaterialIcon
    val alarmOff: IMaterialIcon
    val alarmOn: IMaterialIcon
    val allOut: IMaterialIcon
    val android: IMaterialIcon
    val announcement: IMaterialIcon
    val aspectRatio: IMaterialIcon
    val assessment: IMaterialIcon
    val assignment: IMaterialIcon
    val assignmentInd: IMaterialIcon
    val assignmentLate: IMaterialIcon
    val assignmentReturn: IMaterialIcon
    val assignmentReturned: IMaterialIcon
    val assignmentTurnedIn: IMaterialIcon
    val autorenew: IMaterialIcon
    val backup: IMaterialIcon
    val book: IMaterialIcon
    val bookmark: IMaterialIcon
    val bookmarkBorder: IMaterialIcon
    val bugReport: IMaterialIcon
    val build: IMaterialIcon
    val cached: IMaterialIcon
    val cameraEnhance: IMaterialIcon
    val cardGiftcard: IMaterialIcon
    val cardMembership: IMaterialIcon
    val cardTravel: IMaterialIcon
    val changeHistory: IMaterialIcon
    val checkCircle: IMaterialIcon
    val chromeReaderMode: IMaterialIcon
    val `class`: IMaterialIcon
    val code: IMaterialIcon
    val compareArrows: IMaterialIcon
    val copyright: IMaterialIcon
    val creditCard: IMaterialIcon
    val dashboard: IMaterialIcon
    val dateRange: IMaterialIcon
    val delete: IMaterialIcon
    val description: IMaterialIcon
    val dns: IMaterialIcon
    val done: IMaterialIcon
    val doneAll: IMaterialIcon
    val donutLarge: IMaterialIcon
    val donutSmall: IMaterialIcon
    val eject: IMaterialIcon
    val event: IMaterialIcon
    val eventSeat: IMaterialIcon
    val exitToApp: IMaterialIcon
    val explore: IMaterialIcon
    val extension: IMaterialIcon
    val face: IMaterialIcon
    val favorite: IMaterialIcon
    val favoriteBorder: IMaterialIcon
    val feedback: IMaterialIcon
    val findInPage: IMaterialIcon
    val findReplace: IMaterialIcon
    val fingerprint: IMaterialIcon
    val flightLand: IMaterialIcon
    val flightTakeoff: IMaterialIcon
    val flipToBack: IMaterialIcon
    val flipToFront: IMaterialIcon
    val gavel: IMaterialIcon
    val getApp: IMaterialIcon
    val gif: IMaterialIcon
    val grade: IMaterialIcon
    val groupWork: IMaterialIcon
    val help: IMaterialIcon
    val helpOutline: IMaterialIcon
    val highlightOff: IMaterialIcon
    val history: IMaterialIcon
    val home: IMaterialIcon
    val hourglassEmpty: IMaterialIcon
    val hourglassFull: IMaterialIcon
    val http: IMaterialIcon
    val https: IMaterialIcon
    val importantDevices: IMaterialIcon
    val info: IMaterialIcon
    val infoOutline: IMaterialIcon
    val input: IMaterialIcon
    val invertColors: IMaterialIcon
    val label: IMaterialIcon
    val labelOutline: IMaterialIcon
    val language: IMaterialIcon
    val launch: IMaterialIcon
    val lightbulbOutline: IMaterialIcon
    val lineStyle: IMaterialIcon
    val lineWeight: IMaterialIcon
    val list: IMaterialIcon
    val lock: IMaterialIcon
    val lockOpen: IMaterialIcon
    val lockOutline: IMaterialIcon
    val loyalty: IMaterialIcon
    val markunreadMailbox: IMaterialIcon
    val motorcycle: IMaterialIcon
    val noteAdd: IMaterialIcon
    val offlinePin: IMaterialIcon
    val opacity: IMaterialIcon
    val openInBrowser: IMaterialIcon
    val openInNew: IMaterialIcon
    val openWith: IMaterialIcon
    val pageview: IMaterialIcon
    val panTool: IMaterialIcon
    val payment: IMaterialIcon
    val permCameraMic: IMaterialIcon
    val permContactCalendar: IMaterialIcon
    val permDataSetting: IMaterialIcon
    val permDeviceInformation: IMaterialIcon
    val permIdentity: IMaterialIcon
    val permMedia: IMaterialIcon
    val permPhoneMsg: IMaterialIcon
    val permScanWifi: IMaterialIcon
    val pets: IMaterialIcon
    val pictureInPicture: IMaterialIcon
    val pictureInPictureAlt: IMaterialIcon
    val playForWork: IMaterialIcon
    val polymer: IMaterialIcon
    val powerSettingsNew: IMaterialIcon
    val pregnantWoman: IMaterialIcon
    val print: IMaterialIcon
    val queryBuilder: IMaterialIcon
    val questionAnswer: IMaterialIcon
    val receipt: IMaterialIcon
    val recordVoiceOver: IMaterialIcon
    val redeem: IMaterialIcon
    val reorder: IMaterialIcon
    val reportProblem: IMaterialIcon
    val restore: IMaterialIcon
    val room: IMaterialIcon
    val roundedCorner: IMaterialIcon
    val rowing: IMaterialIcon
    val schedule: IMaterialIcon
    val search: IMaterialIcon
    val settings: IMaterialIcon
    val settingsApplications: IMaterialIcon
    val settingsBackupRestore: IMaterialIcon
    val settingsBluetooth: IMaterialIcon
    val settingsBrightness: IMaterialIcon
    val settingsCell: IMaterialIcon
    val settingsEthernet: IMaterialIcon
    val settingsInputAntenna: IMaterialIcon
    val settingsInputComponent: IMaterialIcon
    val settingsInputComposite: IMaterialIcon
    val settingsInputHdmi: IMaterialIcon
    val settingsInputSvideo: IMaterialIcon
    val settingsOverscan: IMaterialIcon
    val settingsPhone: IMaterialIcon
    val settingsPower: IMaterialIcon
    val settingsRemote: IMaterialIcon
    val settingsVoice: IMaterialIcon
    val shop: IMaterialIcon
    val shopTwo: IMaterialIcon
    val shoppingBasket: IMaterialIcon
    val shoppingCart: IMaterialIcon
    val speakerNotes: IMaterialIcon
    val spellcheck: IMaterialIcon
    val starRate: IMaterialIcon
    val stars: IMaterialIcon
    val store: IMaterialIcon
    val subject: IMaterialIcon
    val supervisorAccount: IMaterialIcon
    val swapHorizontal: IMaterialIcon
    val swapVertical: IMaterialIcon
    val swapVerticalCircle: IMaterialIcon
    val systemUpdateAlt: IMaterialIcon
    val tab: IMaterialIcon
    val tabUnselected: IMaterialIcon
    val theaters: IMaterialIcon
    val thumbDown: IMaterialIcon
    val thumbUp: IMaterialIcon
    val thumbsUpDown: IMaterialIcon
    val timeline: IMaterialIcon
    val toc: IMaterialIcon
    val today: IMaterialIcon
    val toll: IMaterialIcon
    val touchApp: IMaterialIcon
    val trackChanges: IMaterialIcon
    val translate: IMaterialIcon
    val trendingDown: IMaterialIcon
    val trendingFlat: IMaterialIcon
    val trendingUp: IMaterialIcon
    val turnedIn: IMaterialIcon
    val turnedInNot: IMaterialIcon
    val update: IMaterialIcon
    val verifiedUser: IMaterialIcon
    val viewAgenda: IMaterialIcon
    val viewArray: IMaterialIcon
    val viewCarousel: IMaterialIcon
    val viewColumn: IMaterialIcon
    val viewDay: IMaterialIcon
    val viewHeadline: IMaterialIcon
    val viewList: IMaterialIcon
    val viewModule: IMaterialIcon
    val viewQuilt: IMaterialIcon
    val viewStream: IMaterialIcon
    val viewWeek: IMaterialIcon
    val visibility: IMaterialIcon
    val visibilityOff: IMaterialIcon
    val watchLater: IMaterialIcon
    val work: IMaterialIcon
    val youtubeSearchedFor: IMaterialIcon
    val zoomIn: IMaterialIcon
    val zoomOut: IMaterialIcon
    //endregion

    // region Alert
    val addAlert: IMaterialIcon
    val error: IMaterialIcon
    val errorOutline: IMaterialIcon
    val warning: IMaterialIcon
    //endregion

    // region AV
    val addToQueue: IMaterialIcon
    val airplay: IMaterialIcon
    val album: IMaterialIcon
    val artTrack: IMaterialIcon
    val avTimer: IMaterialIcon
    val closedCaption: IMaterialIcon
    val equalizer: IMaterialIcon
    val explicit: IMaterialIcon
    val fastForward: IMaterialIcon
    val fastRewind: IMaterialIcon
    val fiberDvr: IMaterialIcon
    val fiberManualRecord: IMaterialIcon
    val fiberNew: IMaterialIcon
    val fiberPin: IMaterialIcon
    val fiberSmartRecord: IMaterialIcon
    val forward5: IMaterialIcon
    val forward10: IMaterialIcon
    val forward30: IMaterialIcon
    val games: IMaterialIcon
    val hd: IMaterialIcon
    val hearing: IMaterialIcon
    val highQuality: IMaterialIcon
    val libraryAdd: IMaterialIcon
    val libraryBooks: IMaterialIcon
    val libraryMusic: IMaterialIcon
    val loop: IMaterialIcon
    val mic: IMaterialIcon
    val micNone: IMaterialIcon
    val micOff: IMaterialIcon
    val movie: IMaterialIcon
    val musicVideo: IMaterialIcon
    val newReleases: IMaterialIcon
    val notInterested: IMaterialIcon
    val pause: IMaterialIcon
    val pauseCircleFilled: IMaterialIcon
    val pauseCircleOutline: IMaterialIcon
    val playArrow: IMaterialIcon
    val playCircleFilled: IMaterialIcon
    val playCircleOutline: IMaterialIcon
    val playlistAdd: IMaterialIcon
    val playlistAddCheck: IMaterialIcon
    val playlistPlay: IMaterialIcon
    val queue: IMaterialIcon
    val queueMusic: IMaterialIcon
    val queuePlayNext: IMaterialIcon
    val radio: IMaterialIcon
    val recentActors: IMaterialIcon
    val removeFromQueue: IMaterialIcon
    val repeat: IMaterialIcon
    val repeatOne: IMaterialIcon
    val replay: IMaterialIcon
    val replay5: IMaterialIcon
    val replay10: IMaterialIcon
    val replay30: IMaterialIcon
    val shuffle: IMaterialIcon
    val skipNext: IMaterialIcon
    val skipPrevious: IMaterialIcon
    val slowMotionVideo: IMaterialIcon
    val snooze: IMaterialIcon
    val sortByAlpha: IMaterialIcon
    val stop: IMaterialIcon
    val subscriptions: IMaterialIcon
    val subtitles: IMaterialIcon
    val surroundSound: IMaterialIcon
    val videoLibrary: IMaterialIcon
    val videocam: IMaterialIcon
    val videocamOff: IMaterialIcon
    val volumeDown: IMaterialIcon
    val volumeMute: IMaterialIcon
    val volumeOff: IMaterialIcon
    val volumeUp: IMaterialIcon
    val web: IMaterialIcon
    val webAsset: IMaterialIcon
    //endregion

    // region Communication
    val business: IMaterialIcon
    val call: IMaterialIcon
    val callEnd: IMaterialIcon
    val callMade: IMaterialIcon
    val callMerge: IMaterialIcon
    val callMissed: IMaterialIcon
    val callMissedOutgoing: IMaterialIcon
    val callReceived: IMaterialIcon
    val callSplit: IMaterialIcon
    val chat: IMaterialIcon
    val chatBubble: IMaterialIcon
    val chatBubbleOutline: IMaterialIcon
    val clearAll: IMaterialIcon
    val comment: IMaterialIcon
    val contactMail: IMaterialIcon
    val contactPhone: IMaterialIcon
    val contacts: IMaterialIcon
    val dialerSip: IMaterialIcon
    val dialpad: IMaterialIcon
    val email: IMaterialIcon
    val forum: IMaterialIcon
    val importContacts: IMaterialIcon
    val importExport: IMaterialIcon
    val invertColorsOff: IMaterialIcon
    val liveHelp: IMaterialIcon
    val locationOff: IMaterialIcon
    val locationOn: IMaterialIcon
    val mailOutline: IMaterialIcon
    val message: IMaterialIcon
    val noSim: IMaterialIcon
    val phone: IMaterialIcon
    val phonelinkErase: IMaterialIcon
    val phonelinkLock: IMaterialIcon
    val phonelinkRing: IMaterialIcon
    val phonelinkSetup: IMaterialIcon
    val portableWifiOff: IMaterialIcon
    val presentToAll: IMaterialIcon
    val ringVolume: IMaterialIcon
    val screenShare: IMaterialIcon
    val speakerPhone: IMaterialIcon
    val stayCurrentLandscape: IMaterialIcon
    val stayCurrentPortrait: IMaterialIcon
    val stayPrimaryLandscape: IMaterialIcon
    val stayPrimaryPortrait: IMaterialIcon
    val stopScreenShare: IMaterialIcon
    val swapCalls: IMaterialIcon
    val textsms: IMaterialIcon
    val voicemail: IMaterialIcon
    val vpnKey: IMaterialIcon
    //endregion

    // region Content
    val add: IMaterialIcon
    val addBox: IMaterialIcon
    val addCircle: IMaterialIcon
    val addCircleOutline: IMaterialIcon
    val archive: IMaterialIcon
    val backspace: IMaterialIcon
    val block: IMaterialIcon
    val clear: IMaterialIcon
    val contentCopy: IMaterialIcon
    val contentCut: IMaterialIcon
    val contentPaste: IMaterialIcon
    val create: IMaterialIcon
    val drafts: IMaterialIcon
    val filterList: IMaterialIcon
    val flag: IMaterialIcon
    val fontDownload: IMaterialIcon
    val forward: IMaterialIcon
    val gesture: IMaterialIcon
    val inbox: IMaterialIcon
    val link: IMaterialIcon
    val mail: IMaterialIcon
    val markunread: IMaterialIcon
    val moveToInbox: IMaterialIcon
    val nextWeek: IMaterialIcon
    val redo: IMaterialIcon
    val remove: IMaterialIcon
    val removeCircle: IMaterialIcon
    val removeCircleOutline: IMaterialIcon
    val reply: IMaterialIcon
    val replyAll: IMaterialIcon
    val report: IMaterialIcon
    val save: IMaterialIcon
    val selectAll: IMaterialIcon
    val send: IMaterialIcon
    val sort: IMaterialIcon
    val textFormat: IMaterialIcon
    val unarchive: IMaterialIcon
    val undo: IMaterialIcon
    val weekend: IMaterialIcon
    //endregion

    // region Device
    val accessAlarm: IMaterialIcon
    val accessAlarms: IMaterialIcon
    val accessTime: IMaterialIcon
    val addAlarm: IMaterialIcon
    val airplanemodeActive: IMaterialIcon
    val airplanemodeInactive: IMaterialIcon
    val batteryAlert: IMaterialIcon
    val batteryChargingFull: IMaterialIcon
    val batteryFull: IMaterialIcon
    val batteryStd: IMaterialIcon
    val batteryUnknown: IMaterialIcon
    val bluetooth: IMaterialIcon
    val bluetoothConnected: IMaterialIcon
    val bluetoothDisabled: IMaterialIcon
    val bluetoothSearching: IMaterialIcon
    val brightnessAuto: IMaterialIcon
    val brightnessHigh: IMaterialIcon
    val brightnessLow: IMaterialIcon
    val brightnessMedium: IMaterialIcon
    val dataUsage: IMaterialIcon
    val developerMode: IMaterialIcon
    val devices: IMaterialIcon
    val dvr: IMaterialIcon
    val gpsFixed: IMaterialIcon
    val gpsNotFixed: IMaterialIcon
    val gpsOff: IMaterialIcon
    val graphicEq: IMaterialIcon
    val locationDisabled: IMaterialIcon
    val locationSearching: IMaterialIcon
    val networkCell: IMaterialIcon
    val networkWifi: IMaterialIcon
    val nfc: IMaterialIcon
    val screenLockLandscape: IMaterialIcon
    val screenLockPortrait: IMaterialIcon
    val screenLockRotation: IMaterialIcon
    val screenRotation: IMaterialIcon
    val sdStorage: IMaterialIcon
    val settingsSystemDaydream: IMaterialIcon
    val signalCellular4Bar: IMaterialIcon
    val signalCellularConnectedNoInternet4Bar: IMaterialIcon
    val signalCellularNoSim: IMaterialIcon
    val signalCellularNull: IMaterialIcon
    val signalCellularOff: IMaterialIcon
    val signalWifi4Bar: IMaterialIcon
    val signalWifi4BarLock: IMaterialIcon
    val signalWifiOff: IMaterialIcon
    val storage: IMaterialIcon
    val usb: IMaterialIcon
    val wallpaper: IMaterialIcon
    val widgets: IMaterialIcon
    val wifiLock: IMaterialIcon
    val wifiTethering: IMaterialIcon
    //endregion

    // region Editor
    val attachFile: IMaterialIcon
    val attachMoney: IMaterialIcon
    val borderAll: IMaterialIcon
    val borderBottom: IMaterialIcon
    val borderClear: IMaterialIcon
    val borderColor: IMaterialIcon
    val borderHorizontal: IMaterialIcon
    val borderInner: IMaterialIcon
    val borderLeft: IMaterialIcon
    val borderOuter: IMaterialIcon
    val borderRight: IMaterialIcon
    val borderStyle: IMaterialIcon
    val borderTop: IMaterialIcon
    val borderVertical: IMaterialIcon
    val dragHandle: IMaterialIcon
    val formatAlignCenter: IMaterialIcon
    val formatAlignJustify: IMaterialIcon
    val formatAlignLeft: IMaterialIcon
    val formatAlignRight: IMaterialIcon
    val formatBold: IMaterialIcon
    val formatClear: IMaterialIcon
    val formatColorFill: IMaterialIcon
    val formatColorReset: IMaterialIcon
    val formatColorText: IMaterialIcon
    val formatIndentDecrease: IMaterialIcon
    val formatIndentIncrease: IMaterialIcon
    val formatItalic: IMaterialIcon
    val formatLineSpacing: IMaterialIcon
    val formatListBulleted: IMaterialIcon
    val formatListNumbered: IMaterialIcon
    val formatPaint: IMaterialIcon
    val formatQuote: IMaterialIcon
    val formatShapes: IMaterialIcon
    val formatSize: IMaterialIcon
    val formatStrikethrough: IMaterialIcon
    val formatTextdirectionLToR: IMaterialIcon
    val formatTextdirectionRToL: IMaterialIcon
    val formatUnderlined: IMaterialIcon
    val functions: IMaterialIcon
    val highlight: IMaterialIcon
    val insertChart: IMaterialIcon
    val insertComment: IMaterialIcon
    val insertDriveFile: IMaterialIcon
    val insertEmoticon: IMaterialIcon
    val insertInvitation: IMaterialIcon
    val insertLink: IMaterialIcon
    val insertPhoto: IMaterialIcon
    val linearScale: IMaterialIcon
    val mergeType: IMaterialIcon
    val modeComment: IMaterialIcon
    val modeEdit: IMaterialIcon
    val moneyOff: IMaterialIcon
    val publish: IMaterialIcon
    val shortText: IMaterialIcon
    val spaceBar: IMaterialIcon
    val strikethroughS: IMaterialIcon
    val textFields: IMaterialIcon
    val verticalAlignBottom: IMaterialIcon
    val verticalAlignCenter: IMaterialIcon
    val verticalAlignTop: IMaterialIcon
    val wrapText: IMaterialIcon
    //endregion

    // region File
    val attachment: IMaterialIcon
    val cloud: IMaterialIcon
    val cloudCircle: IMaterialIcon
    val cloudDone: IMaterialIcon
    val cloudDownload: IMaterialIcon
    val cloudOff: IMaterialIcon
    val cloudQueue: IMaterialIcon
    val cloudUpload: IMaterialIcon
    val createNewFolder: IMaterialIcon
    val fileDownload: IMaterialIcon
    val fileUpload: IMaterialIcon
    val folder: IMaterialIcon
    val folderOpen: IMaterialIcon
    val folderShared: IMaterialIcon
    //endregion

    // region Hardware
    val cast: IMaterialIcon
    val castConnected: IMaterialIcon
    val computer: IMaterialIcon
    val desktopMac: IMaterialIcon
    val desktopWindows: IMaterialIcon
    val developerBoard: IMaterialIcon
    val deviceHub: IMaterialIcon
    val devicesOther: IMaterialIcon
    val dock: IMaterialIcon
    val gamepad: IMaterialIcon
    val headset: IMaterialIcon
    val headsetMic: IMaterialIcon
    val keyboard: IMaterialIcon
    val keyboardArrowDown: IMaterialIcon
    val keyboardArrowLeft: IMaterialIcon
    val keyboardArrowRight: IMaterialIcon
    val keyboardArrowUp: IMaterialIcon
    val keyboardBackspace: IMaterialIcon
    val keyboardCapslock: IMaterialIcon
    val keyboardHide: IMaterialIcon
    val keyboardReturn: IMaterialIcon
    val keyboardTab: IMaterialIcon
    val keyboardVoice: IMaterialIcon
    val laptop: IMaterialIcon
    val laptopChromebook: IMaterialIcon
    val laptopMac: IMaterialIcon
    val laptopWindows: IMaterialIcon
    val memory: IMaterialIcon
    val mouse: IMaterialIcon
    val phoneAndroid: IMaterialIcon
    val phoneIphone: IMaterialIcon
    val phonelink: IMaterialIcon
    val phonelinkOff: IMaterialIcon
    val powerInput: IMaterialIcon
    val router: IMaterialIcon
    val scanner: IMaterialIcon
    val security: IMaterialIcon
    val simCard: IMaterialIcon
    val smartphone: IMaterialIcon
    val speaker: IMaterialIcon
    val speakerGroup: IMaterialIcon
    val tablet: IMaterialIcon
    val tabletAndroid: IMaterialIcon
    val tabletMac: IMaterialIcon
    val toys: IMaterialIcon
    val tv: IMaterialIcon
    val videogameAsset: IMaterialIcon
    val watch: IMaterialIcon
    //endregion

    // region Image
    val addAPhoto: IMaterialIcon
    val addToPhotos: IMaterialIcon
    val adjust: IMaterialIcon
    val assistant: IMaterialIcon
    val assistantPhoto: IMaterialIcon
    val audiotrack: IMaterialIcon
    val blurCircular: IMaterialIcon
    val blurLinear: IMaterialIcon
    val blurOff: IMaterialIcon
    val blurOn: IMaterialIcon
    val brightness1: IMaterialIcon
    val brightness2: IMaterialIcon
    val brightness3: IMaterialIcon
    val brightness4: IMaterialIcon
    val brightness5: IMaterialIcon
    val brightness6: IMaterialIcon
    val brightness7: IMaterialIcon
    val brokenImage: IMaterialIcon
    val brush: IMaterialIcon
    val camera: IMaterialIcon
    val cameraAlt: IMaterialIcon
    val cameraFront: IMaterialIcon
    val cameraRear: IMaterialIcon
    val cameraRoll: IMaterialIcon
    val centerFocusStrong: IMaterialIcon
    val centerFocusWeak: IMaterialIcon
    val collections: IMaterialIcon
    val collectionsBookmark: IMaterialIcon
    val colorLens: IMaterialIcon
    val colorize: IMaterialIcon
    val compare: IMaterialIcon
    val controlPoint: IMaterialIcon
    val controlPointDuplicate: IMaterialIcon
    val crop: IMaterialIcon
    val crop16_9: IMaterialIcon
    val crop3_2: IMaterialIcon
    val crop5_4: IMaterialIcon
    val crop7_5: IMaterialIcon
    val cropDin: IMaterialIcon
    val cropFree: IMaterialIcon
    val cropLandscape: IMaterialIcon
    val cropOriginal: IMaterialIcon
    val cropPortrait: IMaterialIcon
    val cropRotate: IMaterialIcon
    val cropSquare: IMaterialIcon
    val dehaze: IMaterialIcon
    val details: IMaterialIcon
    val edit: IMaterialIcon
    val exposure: IMaterialIcon
    val exposureNeg1: IMaterialIcon
    val exposureNeg2: IMaterialIcon
    val exposurePlus1: IMaterialIcon
    val exposurePlus2: IMaterialIcon
    val exposureZero: IMaterialIcon
    val filter: IMaterialIcon
    val filter1: IMaterialIcon
    val filter2: IMaterialIcon
    val filter3: IMaterialIcon
    val filter4: IMaterialIcon
    val filter5: IMaterialIcon
    val filter6: IMaterialIcon
    val filter7: IMaterialIcon
    val filter8: IMaterialIcon
    val filter9: IMaterialIcon
    val filter9Plus: IMaterialIcon
    val filterBAndW: IMaterialIcon
    val filterCenterFocus: IMaterialIcon
    val filterDrama: IMaterialIcon
    val filterFrames: IMaterialIcon
    val filterHdr: IMaterialIcon
    val filterNone: IMaterialIcon
    val filterTiltShift: IMaterialIcon
    val filterVintage: IMaterialIcon
    val flare: IMaterialIcon
    val flashAuto: IMaterialIcon
    val flashOff: IMaterialIcon
    val flashOn: IMaterialIcon
    val flip: IMaterialIcon
    val gradient: IMaterialIcon
    val grain: IMaterialIcon
    val gridOff: IMaterialIcon
    val gridOn: IMaterialIcon
    val hdrOff: IMaterialIcon
    val hdrOn: IMaterialIcon
    val hdrStrong: IMaterialIcon
    val hdrWeak: IMaterialIcon
    val healing: IMaterialIcon
    val image: IMaterialIcon
    val imageAspectRatio: IMaterialIcon
    val iso: IMaterialIcon
    val landscape: IMaterialIcon
    val leakAdd: IMaterialIcon
    val leakRemove: IMaterialIcon
    val lens: IMaterialIcon
    val linkedCamera: IMaterialIcon
    val looks: IMaterialIcon
    val looks3: IMaterialIcon
    val looks4: IMaterialIcon
    val looks5: IMaterialIcon
    val looks6: IMaterialIcon
    val looksOne: IMaterialIcon
    val looksTwo: IMaterialIcon
    val loupe: IMaterialIcon
    val monochromePhotos: IMaterialIcon
    val movieCreation: IMaterialIcon
    val movieFilter: IMaterialIcon
    val musicNote: IMaterialIcon
    val nature: IMaterialIcon
    val naturePeople: IMaterialIcon
    val navigateBefore: IMaterialIcon
    val navigateNext: IMaterialIcon
    val palette: IMaterialIcon
    val panorama: IMaterialIcon
    val panoramaFishEye: IMaterialIcon
    val panoramaHorizontal: IMaterialIcon
    val panoramaVertical: IMaterialIcon
    val panoramaWideAngle: IMaterialIcon
    val photo: IMaterialIcon
    val photoAlbum: IMaterialIcon
    val photoCamera: IMaterialIcon
    val photoFilter: IMaterialIcon
    val photoLibrary: IMaterialIcon
    val photoSizeSelectActual: IMaterialIcon
    val photoSizeSelectLarge: IMaterialIcon
    val photoSizeSelectSmall: IMaterialIcon
    val pictureAsPdf: IMaterialIcon
    val portrait: IMaterialIcon
    val removeRedEye: IMaterialIcon
    val rotate90DegreesCcw: IMaterialIcon
    val rotateLeft: IMaterialIcon
    val rotateRight: IMaterialIcon
    val slideshow: IMaterialIcon
    val straighten: IMaterialIcon
    val style: IMaterialIcon
    val switchCamera: IMaterialIcon
    val switchVideo: IMaterialIcon
    val tagFaces: IMaterialIcon
    val texture: IMaterialIcon
    val timelapse: IMaterialIcon
    val timer: IMaterialIcon
    val timer3: IMaterialIcon
    val timer10: IMaterialIcon
    val timerOff: IMaterialIcon
    val tonality: IMaterialIcon
    val transform: IMaterialIcon
    val tune: IMaterialIcon
    val viewComfy: IMaterialIcon
    val viewCompact: IMaterialIcon
    val vignette: IMaterialIcon
    val wbAuto: IMaterialIcon
    val wbCloudy: IMaterialIcon
    val wbIncandescent: IMaterialIcon
    val wbIridescent: IMaterialIcon
    val wbSunny: IMaterialIcon
    //endregion

    // region Maps
    val addLocation: IMaterialIcon
    val beenhere: IMaterialIcon
    val directions: IMaterialIcon
    val directionsBike: IMaterialIcon
    val directionsBoat: IMaterialIcon
    val directionsBus: IMaterialIcon
    val directionsCar: IMaterialIcon
    val directionsRailway: IMaterialIcon
    val directionsRun: IMaterialIcon
    val directionsSubway: IMaterialIcon
    val directionsTransit: IMaterialIcon
    val directionsWalk: IMaterialIcon
    val editLocation: IMaterialIcon
    val flight: IMaterialIcon
    val hotel: IMaterialIcon
    val layers: IMaterialIcon
    val layersClear: IMaterialIcon
    val localActivity: IMaterialIcon
    val localAirport: IMaterialIcon
    val localAtm: IMaterialIcon
    val localBar: IMaterialIcon
    val localCafe: IMaterialIcon
    val localCarWash: IMaterialIcon
    val localConvenienceStore: IMaterialIcon
    val localDining: IMaterialIcon
    val localDrink: IMaterialIcon
    val localFlorist: IMaterialIcon
    val localGasStation: IMaterialIcon
    val localGroceryStore: IMaterialIcon
    val localHospital: IMaterialIcon
    val localHotel: IMaterialIcon
    val localLaundryService: IMaterialIcon
    val localLibrary: IMaterialIcon
    val localMall: IMaterialIcon
    val localMovies: IMaterialIcon
    val localOffer: IMaterialIcon
    val localParking: IMaterialIcon
    val localPharmacy: IMaterialIcon
    val localPhone: IMaterialIcon
    val localPizza: IMaterialIcon
    val localPlay: IMaterialIcon
    val localPostOffice: IMaterialIcon
    val localPrintshop: IMaterialIcon
    val localSee: IMaterialIcon
    val localShipping: IMaterialIcon
    val localTaxi: IMaterialIcon
    val map: IMaterialIcon
    val myLocation: IMaterialIcon
    val navigation: IMaterialIcon
    val nearMe: IMaterialIcon
    val personPin: IMaterialIcon
    val personPinCircle: IMaterialIcon
    val pinDrop: IMaterialIcon
    val place: IMaterialIcon
    val rateReview: IMaterialIcon
    val restaurantMenu: IMaterialIcon
    val satellite: IMaterialIcon
    val storeMallDirectory: IMaterialIcon
    val terrain: IMaterialIcon
    val traffic: IMaterialIcon
    val zoomOutMap: IMaterialIcon
    //endregion

    // region Navigation
    val apps: IMaterialIcon
    val arrowBack: IMaterialIcon
    val arrowDownward: IMaterialIcon
    val arrowDropDown: IMaterialIcon
    val arrowDropDownCircle: IMaterialIcon
    val arrowDropUp: IMaterialIcon
    val arrowForward: IMaterialIcon
    val arrowUpward: IMaterialIcon
    val cancel: IMaterialIcon
    val check: IMaterialIcon
    val chevronLeft: IMaterialIcon
    val chevronRight: IMaterialIcon
    val close: IMaterialIcon
    val expandLess: IMaterialIcon
    val expandMore: IMaterialIcon
    val fullscreen: IMaterialIcon
    val fullscreenExit: IMaterialIcon
    val menu: IMaterialIcon
    val moreHorizontal: IMaterialIcon
    val moreVertical: IMaterialIcon
    val refresh: IMaterialIcon
    val subdirectoryArrowLeft: IMaterialIcon
    val subdirectoryArrowRight: IMaterialIcon
    //endregion

    // region Notification
    val adb: IMaterialIcon
    val airlineSeatFlat: IMaterialIcon
    val airlineSeatFlatAngled: IMaterialIcon
    val airlineSeatIndividualSuite: IMaterialIcon
    val airlineSeatLegroomExtra: IMaterialIcon
    val airlineSeatLegroomNormal: IMaterialIcon
    val airlineSeatLegroomReduced: IMaterialIcon
    val airlineSeatReclineExtra: IMaterialIcon
    val airlineSeatReclineNormal: IMaterialIcon
    val bluetoothAudio: IMaterialIcon
    val confirmationNumber: IMaterialIcon
    val discFull: IMaterialIcon
    val doNotDisturb: IMaterialIcon
    val doNotDisturbAlt: IMaterialIcon
    val driveEta: IMaterialIcon
    val enhancedEncryption: IMaterialIcon
    val eventAvailable: IMaterialIcon
    val eventBusy: IMaterialIcon
    val eventNote: IMaterialIcon
    val folderSpecial: IMaterialIcon
    val liveTv: IMaterialIcon
    val mms: IMaterialIcon
    val more: IMaterialIcon
    val networkCheck: IMaterialIcon
    val networkLocked: IMaterialIcon
    val noEncryption: IMaterialIcon
    val ondemandVideo: IMaterialIcon
    val personalVideo: IMaterialIcon
    val phoneBluetoothSpeaker: IMaterialIcon
    val phoneForwarded: IMaterialIcon
    val phoneInTalk: IMaterialIcon
    val phoneLocked: IMaterialIcon
    val phoneMissed: IMaterialIcon
    val phonePaused: IMaterialIcon
    val power: IMaterialIcon
    val sdCard: IMaterialIcon
    val simCardAlert: IMaterialIcon
    val sms: IMaterialIcon
    val smsFailed: IMaterialIcon
    val sync: IMaterialIcon
    val syncDisabled: IMaterialIcon
    val syncProblem: IMaterialIcon
    val systemUpdate: IMaterialIcon
    val tapAndPlay: IMaterialIcon
    val timeToLeave: IMaterialIcon
    val vibration: IMaterialIcon
    val voiceChat: IMaterialIcon
    val vpnLock: IMaterialIcon
    val wc: IMaterialIcon
    val wifi: IMaterialIcon
    //endregion

    // region Places
    val acUnit: IMaterialIcon
    val airportShuttle: IMaterialIcon
    val allInclusive: IMaterialIcon
    val beachAccess: IMaterialIcon
    val businessCenter: IMaterialIcon
    val casino: IMaterialIcon
    val childCare: IMaterialIcon
    val childFriendly: IMaterialIcon
    val fitnessCenter: IMaterialIcon
    val freeBreakfast: IMaterialIcon
    val golfCourse: IMaterialIcon
    val hotTub: IMaterialIcon
    val kitchen: IMaterialIcon
    val pool: IMaterialIcon
    val roomService: IMaterialIcon
    val rvHookup: IMaterialIcon
    val smokeFree: IMaterialIcon
    val smokingRooms: IMaterialIcon
    val spa: IMaterialIcon
    //endregion

    // region Social
    val cake: IMaterialIcon
    val domain: IMaterialIcon
    val group: IMaterialIcon
    val groupAdd: IMaterialIcon
    val locationCity: IMaterialIcon
    val mood: IMaterialIcon
    val moodBad: IMaterialIcon
    val notifications: IMaterialIcon
    val notificationsActive: IMaterialIcon
    val notificationsNone: IMaterialIcon
    val notificationsOff: IMaterialIcon
    val notificationsPaused: IMaterialIcon
    val pages: IMaterialIcon
    val partyMode: IMaterialIcon
    val people: IMaterialIcon
    val peopleOutline: IMaterialIcon
    val person: IMaterialIcon
    val personAdd: IMaterialIcon
    val personOutline: IMaterialIcon
    val plusOne: IMaterialIcon
    val poll: IMaterialIcon
    val public: IMaterialIcon
    val school: IMaterialIcon
    val share: IMaterialIcon
    val whatshot: IMaterialIcon
    //endregion

    // region Toggle
    val checkBox: IMaterialIcon
    val checkBoxOutlineBlank: IMaterialIcon
    val indeterminateCheckBox: IMaterialIcon
    val radioButtonChecked: IMaterialIcon
    val radioButtonUnchecked: IMaterialIcon
    val star: IMaterialIcon
    val starBorder: IMaterialIcon
    val starHalf: IMaterialIcon
    //endregion
}
